### PR TITLE
Compile with dav1d support

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Needed for https://github.com/conda-forge/staged-recipes/pull/17848

### CODE REVIEW

**Comment by jaimergp** [comment]
@conda-forge-admin, please rerender

**Comment by jaimergp** [comment]
Unclear why it cannot find `dav1d` for ARM64, when we can see [it's there](https://anaconda.org/conda-forge/dav1d/files) 🤷  CDN sync issue?

**Comment by hmaarrfk** [comment]
maybe. should we just release uild 2 of that small package?

**Comment by jaimergp** [comment]
It was due to the CDN outage this weekend. Re-running all jobs!

**Review by carterbox — APPROVED** [review]

**Pull request merged**
